### ISSUE TITLE
Does not react to anything

### ISSUE THREAD

**Issue by idkCpp** [fabianf1/Curve-Project#1]
I compiled the program and started it and came to the main menu. But from there nothing happens.

The `eventHandler` method in `Main.cpp:50` does not even care about any kind of event. I debugged it and it went straight to line `Main.cpp:61` but `game.joinGame` was false, so it returned immediately on every possible event.

**Comment by fabianf1** [comment]
In my setup with SFML 2.3.2 and TDM GCC 5.1.0 as compiler everything works as expected.
Can you give me some information about your setup?

Relating to `game.joinGame`, it should become true if you click "Join game" in the main menu, after which a text field appears, together with a join button.

**Comment by idkCpp** [comment]
About the setup:
**OS**: Debian 8 Jessie
**SFML**: `2.1+dfsg2-1+b2` 
**Compiler**: `g++ (Debian 4.9.2-10) 4.9.2`
About the resources: I have no clue what you used to embed the resources into the executable, and I also saw that the Linux implementation of the `Resource` class was missing, so I just implemented it so that it would just ask for the file name when the `Resource::getImage(const std::string&)` method is invoked.

So I get to the main menu screen. 
I assume the event handler is the only function that handles the SFML events.
Going through this function step by step:
It is a massive if-elseif-else statement.
- `if (event.type == sf::Event::Closed)` nope, I pressed a mouse button
- `else if(event.type == sf::Event::LostFocus && ...)` nope
- `else if(game.mode == Game::Mode::mainMenu)` this matches because `game.mode` is initially set to `mainMenu`.

Looking at this block
```
    else if(game.mode == Game::Mode::mainMenu){
        if(game.joinGame){
            if(event.type == sf::Event::TextEntered && ( (event.text.unicode >= 48 && event.text.unicode <= 57) || event.text.unicode==46 ) && game.serverIp.size()<15){
                game.serverIp+=static_cast<char>(event.text.unicode);
            }
            else if( (event.type == sf::Event::KeyPressed) && (event.key.code == sf::Keyboard::BackSpace) && (game.serverIp.size() > 0) ){
                game.serverIp.erase(game.serverIp.size()-1,1);
            }
        }
    }
```
So if `game.joinGame` only becomes `true` when you click, where is the click handled?

**Comment by fabianf1** [comment]
I used an .rc file for the resources that works fine in Windows, but not on Linux. I wanted to implement things for Linux, but I still haven't done that as can be seen in `classes/Resource.cpp:57`. So, currently the resources will not load in Linux.

For the clicking events, eventHandler does not handle them. If you look further in the main loop you arrive at
```
for(unsigned int i=0; i<storage.objects.size();i++){
    if(storage.objects[i]->checkVisible(*this)){
        storage.objects[i]->process(*this);
    }
}
```
This part does process all events that happen at every object, like the buttons and text.
The definition for the join game button object starts at `classes/ObjectStorage.cpp:47`, where there is the following lambda function: 
```
    action = [](Main &main, ObjectButton<sf::Text> &button){
        // Open IP Prompt
        //button.activated=!button.activated;
        main.game.joinGame=!main.game.joinGame;
    };
```
This lambda function should be triggered by the following part in `classes/ObjectButton.cpp`:
```
 if(drawable.getGlobalBounds().contains(sf::Mouse::getPosition(window).x,sf::Mouse::getPosition(window).y)){
        drawable.setColor(selectedColor);
        if(!activated){
            drawable.setStyle(selectedStyle);
        }
        else{
            drawable.setStyle(selectedStyle|activatedStyle);
        }
        if(window.hasFocus()&&sf::Mouse::isButtonPressed(sf::Mouse::Left) && lastClick.getElapsedTime().asSeconds()>0.15){
            lastClick.restart();
            return true;
        }
}
```
So if the mouse is within the containing rectangle of the button, the window has focus and the mouse is clicked the function where the above code is in returns true, and the update lambda function should be run. Therefore, `game.joinGame` should be set to true or false if its triggered.

**Comment by idkCpp** [comment]
I'd really love to build on your code, but it just gives me headaches... 

How did you do the collision detection?

**Comment by fabianf1** [comment]
I can understand. It would code this game differently nowadays :)

`classes/Game.cpp:255` does the hit detection.
It checks for out of bounds and line hit detection.
There are some special cases for head on detection and the player's own line is also processed separately. 
The last case is a bit messy though.
